import sys
import os
from time import sleep


def abcd():
  print ('\n\n\n\n')
  os.system('clear')
  print ('  \n\n\n Starting fcracker.../')
  sleep(0.015)
  os.system('clear')
  print ('  \n\n\n sTarting fcracker...|')
  sleep(0.015)
  os.system('clear')
  print ('  \n\n\n stArting fcracker...-')
  sleep(0.015)
  os.system('clear')
  print ("  \n\n\n staRting fcracker...\\")
  sleep(0.015)
  os.system('clear')
  print ("  \n\n\n starTing fcracker...-")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n startIng fcracker.../")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n startiNg fcracker...|")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n startinG fcracker...-")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting Fcracker...\\")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting fCracker...-")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting fcRacker.../")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting fcrAcker...|")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting fcraCker...-")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting fcracKer.../")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting fcrackEr...\\")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting fcrackeR...-")
  sleep(0.15)
  os.system('clear')
  print ('  \n\n\n Starting fcracker.../')
  sleep(0.15)
  os.system('clear')
  print ('  \n\n\n sTarting fcracker...|')
  sleep(0.15)
  os.system('clear')
  print ('  \n\n\n stArting fcracker...-')
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n staRting fcracker...\\")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starTing fcracker...-")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n startIng fcracker.../")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n startiNg fcracker...|")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n startinG fcracker...-")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting Fcracker...\\")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting fCracker...-")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting fcRacker.../")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting fcrAcker...|")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting fcraCker...-")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting fcracKer.../")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting fcrackEr...\\")
  sleep(0.15)
  os.system('clear')
  print ("  \n\n\n starting fcrackeR...-")
  sleep(0.15)
  os.system('clear')
